import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Lens App</title>
        <meta name="description" content="Generated by create lens app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://docs.lens.xyz/docs/sdk-react-intro?utm_source=create-lens-app&utm_campaign=create-lens-app"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.docsLink}
            >
              Lens Docs
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/lens-illus.png"
            alt="Next.js Logo"
            width={600}
            height={450}
            priority
            draggable={false}
          />
        </div>

        <div className={styles.grid}>
          <a
            href="/feed"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              User Feed <span>-&gt;</span>
            </h2>
          </a>

          <a
            href="/profiles"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Profiles <span>-&gt;</span>
            </h2>
          </a>

          <a
            href="/publications"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Publications <span>-&gt;</span>
            </h2>
          </a>
        </div>
      </main>
    </>
  );
}
